#!/bin/bash

mkdir -p ~/.config/Mutate
cp -R /usr/share/mutate/config/* ~/.config/Mutate
chmod -R a+x ~/.config/Mutate/scripts
chmod -R a+w ~/.config/Mutate
sed -i "s|{home}|$HOME|g" ~/.config/Mutate/config.ini
