Document: mutate
Title: Debian mutate Manual
Author: <insert document author here>
Abstract: This manual describes what mutate is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mutate/mutate.sgml.gz

Format: postscript
Files: /usr/share/doc/mutate/mutate.ps.gz

Format: text
Files: /usr/share/doc/mutate/mutate.text.gz

Format: HTML
Index: /usr/share/doc/mutate/html/index.html
Files: /usr/share/doc/mutate/html/*.html
