#!/bin/sh
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH
/build/configure
make && make install
for i in `ls /home`; do
mkdir -p /home/$i/.config/Mutate
cp -r /config/* /home/$i/.config/Mutate
cat /config/config.ini | sed "s#{home}#`echo /home/$i`#g" > /home/$i/.config/Mutate/config.ini
done
cp /info/mutate.png /usr/share/icons
cp /info/Mutate.desktop /usr/share/applications
make clean
rm -rf mutate Mutate config build info Makefile
